require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'bruh_morning' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])


  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  pod 'react-native-notification-sounds', :path => '../node_modules/react-native-notification-sounds'


  pod 'react-native-alarm-notification', :path => '../node_modules/react-native-alarm-notification'

  target 'bruh_morningTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'bruh_morning-tvOS' do
  # Pods for bruh_morning-tvOS

  target 'bruh_morning-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
